name: chat_bird
description: Chat and calling open source app for flutter community

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ScreenUtil
  flutter_screenutil: ^5.6.0

  #Bloc
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mockito: ^5.3.2

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
